FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive \
    MYSQL_HOST=127.0.0.1 \
    MYSQL_PORT=3306 \
    MYSQL_NAME=webserver \
    MYSQL_LOGIN=root \
    MYSQL_PASSWORD=admin \
    QUEUE_HOST=kafka \
    QUEUE_TOPIC=webserver \
    QUEUE_GROUP_ID=0

RUN apt-get update -y && apt-get install -y \
    git \
    cmake \
    g++ \
    libpoco-dev \
    libboost-all-dev \
    librdkafka-dev

RUN git clone https://github.com/mfontanini/cppkafka && cd cppkafka && mkdir build && cd build && cmake .. && make && make install


COPY web_server /web_server

WORKDIR /web_server/build

RUN cmake .. && cmake --build . --target event_writer -j 9

CMD /web_server/build/event_writer \
 --host=$MYSQL_HOST\
 --port=$MYSQL_PORT\
 --login=$MYSQL_LOGIN\
 --password=$MYSQL_PASSWORD \
 --database=$MYSQL_NAME\
 --queue=$QUEUE_HOST \
 --topic=$QUEUE_TOPIC \
 --group_id=$QUEUE_GROUP_ID